spring:
  profiles:
    active: production
---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/ktpm_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  welcome:
    message: 'welcome to production'

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/ktpm_db_dev
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  welcome:
    message: 'welcome to dev'